# Generated by Django 4.2.2 on 2023-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_blogpost_comment_blogpost_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='post.comment'),
        ),
    ]
