# Generated by Django 4.2.2 on 2023-06-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_blogpost_comment_comment_blog_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_post',
            new_name='blog',
        ),
    ]
