# Generated by Django 4.2.2 on 2023-06-28 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0005_rename_blog_post_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='title',
        ),
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='enter your topic', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default='enter your description', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='enter your title', max_length=120),
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='topic',
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.topic'),
        ),
    ]
