# Generated by Django 4.2.2 on 2023-06-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_topic_title_topic_name_alter_blogpost_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic',
        ),
    ]
